#*****************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# build.tcl: Tcl script for re-creating project 'project_ConmutMatrix'
#
# Generated by Vivado on Wed Jan 15 18:52:53 -0300 2025
# IP Build 4028589 on Sat Oct 14 00:45:43 MDT 2023
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "F:/Proyecto_Final/repo/FinalProject_Ing/project_ConmutMatrix/project_ConmutMatrix.srcs/sources_1/bd/designMod_1/designMod_1.bd"
#    "F:/Proyecto_Final/repo/FinalProject_Ing/project_ConmutMatrix/project_ConmutMatrix.srcs/utils_1/imports/synth_1/Modulador.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    "F:/Proyecto_Final/repo/FinalProject_Ing/HW/src/hdl/red_sector.vhd"
#    "F:/Proyecto_Final/repo/FinalProject_Ing/HW/src/hdl/Modulador.vhd"
#    "F:/Proyecto_Final/repo/FinalProject_Ing/HW/src/hdl/Declaraciones.vhd"
#    "F:/Proyecto_Final/repo/FinalProject_Ing/HW/src/tb/Tb_Modulador_1.vhd"
#
#*****************************************************************************************

# # Check file required for this script exists
# proc checkRequiredFiles { origin_dir} {
#   set status true
#   set files [list \
#  "[file normalize "$origin_dir/project_ConmutMatrix/project_ConmutMatrix.srcs/sources_1/bd/designMod_1/designMod_1.bd"]"\
#  "[file normalize "$origin_dir/project_ConmutMatrix/project_ConmutMatrix.srcs/utils_1/imports/synth_1/Modulador.dcp"]"\
#   ]
#   foreach ifile $files {
#     if { ![file isfile $ifile] } {
#       puts " Could not find local file $ifile "
#       set status false
#     }
#   }

#   set files [list \
#  "[file normalize "$origin_dir/HW/src/hdl/red_sector.vhd"]"\
#  "[file normalize "$origin_dir/HW/src/hdl/Modulador.vhd"]"\
#  "[file normalize "$origin_dir/HW/src/hdl/Declaraciones.vhd"]"\
#  "[file normalize "$origin_dir/HW/src/tb/Tb_Modulador_1.vhd"]"\
#   ]
#   foreach ifile $files {
#     if { ![file isfile $ifile] } {
#       puts " Could not find remote file $ifile "
#       set status false
#     }
#   }

#   return $status
# }
# Set the reference directory for source file relative paths (by default the value is script directory path)

# Check the version of Vivado used
set version_required "2023.2"
set ver [lindex [split $::env(XILINX_VIVADO) /] 3]
if {![string equal $ver $version_required]} {
  puts "###############################"
  puts "### Failed to build project ###"
  puts "###############################"
  puts "This project was designed for use with Vivado $version_required."
  puts "You are using Vivado $ver. Please install Vivado $version_required,"
  puts "or download the project sources from a commit of the Git repository"
  puts "that was intended for your version of Vivado ($ver)."
  return
}

set _xil_proj_name_ "project_ConmutMatrix"

set origin_dir [file dirname [info script]]
set orig_proj_dir "[file normalize "$origin_dir/$_xil_proj_name_"]"

puts "Direccion origen: $origin_dir"
puts "Direccion origen de projecto: $orig_proj_dir"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z007sclg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "realdigital.org:blackboard_d:part0:1.2" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "feature_set" -value "FeatureSet_Classic" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "platform.board_id" -value "blackboard_d" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
  [file normalize "${origin_dir}/HW/src/hdl/red_sector.vhd"] \
  [file normalize "${origin_dir}/HW/src/hdl/Modulador.vhd"] \
  [file normalize "${origin_dir}/HW/src/hdl/Declaraciones.vhd"] \
 ]
 add_files -norecurse -fileset $obj $files

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/HW/src/ip_repo/"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "modulador" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# # Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/HW/src/tb/Tb_Modulador_1.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "tb_modulador" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z007sclg400-1 -flow {Vivado Synthesis 2023} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2023" [get_runs synth_1]
}

set obj [get_runs synth_1]

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z007sclg400-1 -flow {Vivado Implementation 2023} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2023" [get_runs impl_1]
}
set obj [get_runs impl_1]

set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"